// 订单模块
export const PUSH_ORDER_LIST_ALL = 'PUSH_ORDER_LIST_ALL'
export const PUSH_ORDER_LIST_FINISHED = 'PUSH_ORDER_LIST_FINISHED'
export const PUSH_ORDER_LIST_UNFINISHED = 'PUSH_ORDER_LIST_UNFINISHED'
// 过滤的场地数组
export const PUSH_STORE_AREA_LIST = 'PUSH_STORE_AREA_LIST'

// 场地模块
export const PUSH_SPACE_LIST = 'PUSH_SPACE_LIST'
export const PUSH_TYPE_LIST = 'PUSH_TYPE_LIST'
export const PUSH_SPACE_DETAIL = 'PUSH_SPACE_DETAIL'
export const PUSH_SPACE_BASE = 'PUSH_SPACE_BASE'
export const PUSH_SPACE_CLASS = 'PUSH_SPACE_CLASS'

// 结算模块
export const PUSH_COUNT_LIST = 'PUSH_COUNT_LIST'

// 个人中心模块
export const PUSH_USER_TOKEN = 'PUSH_USER_TOKEN'
export const PUSH_MY_CORE_PROFILE = 'PUSH_MY_CORE_PROFILE'

// 公共模块
export const LOADINGTRUE = 'LOADINGTRUE'
export const LOADINGFALSE = 'LOADINGFALSE'