export default {
  // 获取场地类型列表
  getAreaTypeList: '/v1/area_app/getAreaTypeList',
  // 添加场地（第一步）
  addStoreArea: '/v1/area_app/addStoreArea',
  // 更新场地（第二步）
  updateStoreArea: '/v1/area_app/updateStoreArea',
  // 删除场地
  deleteStoreArea: '/v1/area_app/deleteStoreArea',
  // 更新课程状态
  updateStoreClassSetStatus: '/v1/area_app/updateStoreClassSetStatus',
  // 查询场地详情
  getStoreAreaInfo: '/v1/area_app/getStoreAreaInfo',
  // 修改场地空间信息
  updateStoreSpace: '/v1/area_app/updateStoreSpace',
  // 删除场地空间信息
  deleteStoreSpace: '/v1/area_app/deleteStoreSpace',
  // 订单列表
  getAreaOrderList: '/v1/area_app/getAreaOrderList',
  // 场地列表
  getStoreAreaList: '/v1/area_app/getStoreAreaList',
  // 场地筛选条件
  getConditionStoreAreaList: '/v1/area_app/getConditionStoreAreaList',
  // 个人中心
  getMyCoreProfile: '/v1/area_app/getMyCoreProfile',
  // 结算统计
  getBalanceCountArea: '/v1/area_app/getBalanceCountArea',
  // 设置收款信息
  addPaymentAccountInfoSet: '/v1/area_app/addPaymentAccountInfoSet',
  // 更新收款信息
  updatePaymentAccountInfo: '/v1/area_app/updatePaymentAccountInfo',
  // 获取收款信息
  getPaymentAccountInfo: '/v1/area_app/getPaymentAccountInfo',
  getUploadToken: 'upload/qiniu/upToken',
  getStoreClassSet: '/v1/area_app/getStoreClassSet'
}
